replicaCount: 1

image:
  repository: docker.io/inwerejosic/flask-ip-reverse
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
# 0YUgL0YxTqQy4vPG