services:
  web:
    build: .
    image: flask-ip-reverse:1.0
    container_name: flask-ip-reverse
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
