grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalServiceMonitors:
      - name: flask-ip-reverse
        selector:
          matchLabels:
            app: flask-ip-reverse
        endpoints:
          - port: 5000
            path: /metrics
            interval: 15s

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: true
