apiVersion: v2
name: flask-ip-reverse
description: Minimal Flask app with Prometheus uptime monitoring
type: application
version: 1.0.0
appVersion: "1.1"

dependencies:
  - name: kube-prometheus-stack
    version: "45.7.1"
    repository: "https://prometheus-community.github.io/helm-charts"

