replicaCount: 1
image:
  repository: docker.io/inwerejosic/flask-ip-reverse
  tag: "1.1"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 5000
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics
