# Flask app
replicaCount: 1
image:
  repository: inwerejosic/flask-ip-reverse
  tag: "1.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

resources: {}
nodeSelector: {}
tolerations: []
affinity: []

# ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics
