apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-ip-reverse.fullname" . }}
  namespace: actix
  labels:
    app: {{ include "flask-ip-reverse.name" . }}
    managed-by: argocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-ip-reverse.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-ip-reverse.name" . }}
        managed-by: argocd
    spec:
      containers:
        - name: flask-ip-reverse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
