{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-ip-reverse.fullname" . }}
  namespace: actix
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "flask-ip-reverse.name" . }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
