apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-ip-reverse.fullname" . }}
  namespace: actix
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "flask-ip-reverse.name" . }}
  endpoints:
    - port: http                 # <-- must match Service port name
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
