{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-ip-reverse.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "flask-ip-reverse.name" . }}
  endpoints:
    - port: http
      interval: 30s
      path: /healthz
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "flask-ip-reverse.fullname" . }}-alerts
spec:
  groups:
    - name: flask-ip-reverse.rules
      rules:
        - alert: FlaskAppDown
          expr: absent(up{job="{{ include "flask-ip-reverse.fullname" . }}"} == 1)
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Flask IP Reverse app is down"
            description: "No healthy pods of {{ include "flask-ip-reverse.fullname" . }} detected in namespace {{ .Release.Namespace }}."
{{- end }}
