apiVersion: v2
name: flask-ip-reverse
description: A Flask app with monitoring via kube-prometheus-stack
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: "73.10.0"
    repository: "https://prometheus-community.github.io/helm-charts"
