replicaCount: 1

image:
  repository: docker.io/inwerejosic/flask-ip-reverse
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# kube-prometheus-stack minimal settings
kube-prometheus-stack:
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin
    service:
      type: LoadBalancer
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      additionalServiceMonitors:
        - name: flask-ip-reverse
          selector:
            matchLabels:
              app: flask-ip-reverse
          endpoints:
            - port: 5000
              path: /metrics
              interval: 15s
