name: Build and Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set Docker image tags
      - name: Set image tags
        id: vars
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/flask-ip-reverse
          # Always build with :latest and commit SHA
          TAGS="$IMAGE_NAME:latest,$IMAGE_NAME:${GITHUB_SHA}"
          # If this is a tagged release, add version tag too
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/v}
            TAGS="$TAGS,$IMAGE_NAME:$VERSION_TAG"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tags }}


# name: Test Docker Login

# on: [push]

# jobs:
#   docker-login:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Confirm login
#         run: docker info
